use_frameworks!

platform :ios, '9.0'

target 'LSYRegister_Example' do
  pod 'LSYRegister', :path => '../'
  pod 'LSYLogin', :path => '../../LSYLogin'
  
  target 'LSYRegister_Tests' do
    inherit! :search_paths

    
  end
end
